import type { CanonicalProject, CanonicalWorkItem } from "@frontstage/integration-core";

/**
 * Official-shaped demo workspace for local development before OAuth
 * credentials exist. Content follows the brief's demo direction (§61):
 * messy, realistic internal engineering work that a client should never
 * see raw.
 */

export const FIXTURE_WORKSPACE = {
  id: "fixture-workspace-northline",
  name: "Northline Product Studio (Linear)",
};

export const FIXTURE_PROJECTS: CanonicalProject[] = [
  {
    id: "lin-prj-credentialing",
    name: "Credentialing Modernization",
    description:
      "Replace the legacy credential verification pipeline. Waves: retry handling, validation messaging, telemetry, dashboard.",
    state: "started",
    targetDate: "2026-09-30",
    url: "https://linear.app/northline/project/credentialing",
    updatedAt: "2026-07-14T18:22:00.000Z",
  },
  {
    id: "lin-prj-compliance",
    name: "Compliance Reporting",
    description: "Quarterly compliance export pipeline and evidence archive.",
    state: "backlog",
    targetDate: "2026-11-15",
    url: "https://linear.app/northline/project/compliance",
    updatedAt: "2026-07-10T09:00:00.000Z",
  },
];

export const FIXTURE_ISSUES: CanonicalWorkItem[] = [
  {
    id: "lin-eng-42",
    identifier: "ENG-42",
    projectId: "lin-prj-credentialing",
    title: "Add transaction retry handling w/ jittered backoff in verifier worker",
    description:
      "psync gateway 502s under load. Wrap verify() in retry (max 5, expo+jitter). NOTE: first attempt with p-retry deadlocked the pool — see thread. DO NOT retry on 4xx.",
    stateType: "started",
    stateName: "In Progress",
    priority: 2,
    assigneeName: "Priya N.",
    labels: ["backend", "credentialing", "tech-debt"],
    estimate: 5,
    url: "https://linear.app/northline/issue/ENG-42",
    updatedAt: "2026-07-14T17:05:00.000Z",
  },
  {
    id: "lin-eng-43",
    identifier: "ENG-43",
    projectId: "lin-prj-credentialing",
    title: "Expand integration tests for credential validation edge cases",
    description:
      "Cover: expired NPI, dual-state licenses, unicode names, the cursed '00000000' provider id. Mock psync properly this time.",
    stateType: "started",
    stateName: "In Progress",
    priority: 3,
    assigneeName: "Marcus T.",
    labels: ["testing", "credentialing"],
    estimate: 3,
    url: "https://linear.app/northline/issue/ENG-43",
    updatedAt: "2026-07-13T11:40:00.000Z",
  },
  {
    id: "lin-eng-44",
    identifier: "ENG-44",
    projectId: "lin-prj-credentialing",
    title: "Improve credential validation failure message (user-facing copy)",
    description:
      "Current error: 'VALIDATION_ERR_17'. Product wants human copy + retry CTA. Blocked on legal reviewing wording for denial reasons.",
    stateType: "backlog",
    stateName: "Todo",
    priority: 2,
    assigneeName: "Priya N.",
    labels: ["frontend", "copy", "blocked-legal"],
    estimate: 2,
    url: "https://linear.app/northline/issue/ENG-44",
    updatedAt: "2026-07-12T15:00:00.000Z",
  },
  {
    id: "lin-eng-45",
    identifier: "ENG-45",
    projectId: "lin-prj-credentialing",
    title: "Add failed-check telemetry + Grafana panel",
    description: "Emit counter per failure class. Wire to existing OTel pipeline.",
    stateType: "completed",
    stateName: "Done",
    priority: 3,
    assigneeName: "Marcus T.",
    labels: ["observability"],
    estimate: 2,
    url: "https://linear.app/northline/issue/ENG-45",
    updatedAt: "2026-07-11T10:12:00.000Z",
  },
  {
    id: "lin-eng-46",
    identifier: "ENG-46",
    projectId: "lin-prj-credentialing",
    title: "SPIKE: evaluate dropping psync for direct NPPES sync (FAILED — do not revisit until Q4)",
    description:
      "Spent 3 days. NPPES bulk file is 9GB weekly, no delta API. Killing this. Keeping notes for Q4 capacity discussion.",
    stateType: "canceled",
    stateName: "Canceled",
    priority: 4,
    assigneeName: "Priya N.",
    labels: ["spike", "do-not-share"],
    url: "https://linear.app/northline/issue/ENG-46",
    updatedAt: "2026-07-09T16:45:00.000Z",
  },
  {
    id: "lin-eng-47",
    identifier: "ENG-47",
    projectId: "lin-prj-credentialing",
    title: "Credential status dashboard — client-facing v1",
    description: "Read model + status page. Depends on ENG-42 retry semantics landing first.",
    stateType: "unstarted",
    stateName: "Todo",
    priority: 2,
    assigneeName: "Dana K.",
    labels: ["frontend", "credentialing"],
    estimate: 8,
    url: "https://linear.app/northline/issue/ENG-47",
    updatedAt: "2026-07-14T09:30:00.000Z",
  },
  {
    id: "lin-eng-48",
    identifier: "ENG-48",
    projectId: "lin-prj-credentialing",
    title: "Verify webhook HMAC before we get pwned",
    description: "We currently trust any POST. Fix before pilot. Embarrassing.",
    stateType: "triage",
    stateName: "Triage",
    priority: 1,
    labels: ["security", "do-not-share"],
    url: "https://linear.app/northline/issue/ENG-48",
    updatedAt: "2026-07-15T07:50:00.000Z",
  },
  {
    id: "lin-ops-21",
    identifier: "OPS-21",
    projectId: "lin-prj-credentialing",
    title: "Deploy verifier worker to prod + canary config",
    description: "Blue/green with 10% canary. Needs ENG-42.",
    stateType: "unstarted",
    stateName: "Todo",
    priority: 2,
    assigneeName: "Dana K.",
    labels: ["ops", "deploy"],
    estimate: 3,
    url: "https://linear.app/northline/issue/OPS-21",
    updatedAt: "2026-07-13T14:20:00.000Z",
  },
  {
    id: "lin-eng-60",
    identifier: "ENG-60",
    projectId: "lin-prj-compliance",
    title: "Design quarterly export schema (parquet vs csv, argh)",
    description: "Auditor wants csv. Data eng wants parquet. Both, probably.",
    stateType: "backlog",
    stateName: "Todo",
    priority: 3,
    assigneeName: "Marcus T.",
    labels: ["compliance", "data"],
    url: "https://linear.app/northline/issue/ENG-60",
    updatedAt: "2026-07-08T10:00:00.000Z",
  },
  {
    id: "lin-eng-61",
    identifier: "ENG-61",
    projectId: "lin-prj-compliance",
    title: "Evidence archive retention policy enforcement",
    description: "7yr retention, legal hold override. Needs product sign-off.",
    stateType: "backlog",
    stateName: "Todo",
    priority: 3,
    labels: ["compliance"],
    url: "https://linear.app/northline/issue/ENG-61",
    updatedAt: "2026-07-07T13:30:00.000Z",
  },
];
